# 数据库信息配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myself
    username: root
    password: Abcd123
    driver-class-name: com.mysql.jdbc.Driver

# JPA 属性设置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true